spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret: G
            scope:
              - email
              - profile

jwt:
  issuer: test@test.com
  secret_key:
    
